project:
  type: website
  output-dir: docs

website:
 # title: "Jacey C. Van Wert"
  navbar:
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - research.qmd
      - community.qmd
      - href: cv/vanwert_cv.pdf
        text: cv

      
  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Jacey Van Wert"
    right: 
      - icon: github
        href: https://github.com/jcvanwert
      - icon: twitter
        href: https://twitter.com/jacey_van_wert
      #  - icon: researchgate
      #    href: https://www.researchgate.net/profile/Jacey-Van-Wert?ev=hdr_xprf
      # - icon: google-scholar
      #   href: https://scholar.google.com/citations?user=R_tz8jMAAAAJ&hl=en
     
  reader-mode: true

format:
  html:
    page-layout: full
    theme: 
    - oceans.scss
    # css: styles.css
    toc: true

editor: visual

