---
title: "PhD metrics"
output: html_document
date: "2023-06-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(sf)
library("rnaturalearth")
library("rnaturalearthdata")
library(here)
library(ggthemes)
library(dplyr)
library(stringr)

```

## Map

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
collabs <- read.csv(here("phd-metrics", "map", "collabs-coordinates.csv"))

collabs_maps <- ggplot() +
    geom_sf(data = world, color = "black", fill = "snow1")+
  coord_sf(xlim= c(-180, 180), ylim = c(-50, 80))+
    geom_point(data = collabs, aes(y = lat, x = long, size = Count), color = "#c7949b", alpha = .6)+
    ggtitle("PhD Collaborations")+
  scale_size(range=c(3, 5), breaks=c(1, 5, 10, 15))+
    theme_map()+
    theme(plot.title = element_text(colour = "snow1", size =20),
          legend.background = element_rect(fill="transparent"),
          legend.title = element_text(color = "snow1"),
          legend.text = element_text(color = "snow1"),
          legend.key = element_rect(fill = "transparent"))

ggsave(here("phd-metrics", "map", "map_collabs.png"), height = 8, width = 8)


```

## Presentations

```{r}
pres <- read.csv(here("phd-metrics", "plots", "presentations.csv"))

pres_count <- pres %>%
  dplyr::count(presentation_type)%>%
  filter(n<100)

x<-ggplot(pres_count, aes(x = presentation_type, y = n))+
  geom_col(fill = "#c7949b", width = 0.6)+
  labs(y = "Number", x = "\nPresentation type")+
  ggtitle("Presentations throughout PhD")+
  scale_y_continuous(breaks = c(0, 5, 10))+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))+
  theme(
  panel.background = element_rect(fill = "transparent",
                                  colour = NA_character_), # necessary to avoid drawing panel outline
  panel.grid.major = element_blank(), # get rid of major grid
  panel.grid.minor = element_blank(), # get rid of minor grid
  plot.background = element_rect(fill = "transparent",
                                 colour = NA_character_), # necessary to avoid drawing plot outline
  legend.background = element_rect(fill = "transparent"),
  legend.box.background = element_rect(fill = "transparent"),
  legend.key = element_rect(fill = "transparent"))+
  theme(text=element_text(size=20), #change font size of all text
        axis.text=element_text(size=20), #change font size of axis text
        axis.title=element_text(size=20, color = "snow1"), #change font size of axis titles
        plot.title=element_text(size=24, color = "snow1"), #change font size of plot title
        legend.text=element_text(size=20), #change font size of legend text
        legend.title=element_text(size=20), #change font size of legend title   
        axis.text.x=element_text(colour="snow1"),
        axis.text.y=element_text(colour="snow1")  )
ggsave(here("phd-metrics", "plots", "presentations.png"), width = 10, height = 8)

```
